### ISSUE TITLE
dude wtf 

### ISSUE THREAD

**Issue by MXNOSKID** [akineechan/Hexen-Base#1]
Nachdem ich das gesehen habe würde ich sogar freiwillig zu Nano42 wechseln

**Comment by akineechan** [comment]
und wieso macht man dafür ein issue auf? niemand zwingt dich diese base zu usen

**Comment by PatchByte** [comment]
joa er will einfach nur sagen das sie scheiße geordnet ist und dein script fiber nicht geht lolz
